<?php
    require "auxiliar/header.phtml";
?>
    <div class="container">
        <div class="row">
           <div class="col-md-6 offset-md-4">
                <div class="card" style="width: 18rem; margin-top: 150px;">
                    <div class="card-body">
                        <form action="/sitefree_api/public/api/token" method="post">
                            <div class="form-group">
                            <label for="Login">Login</label>
                            <input type="text" class="form-group" name="email"/>
                            </div>
                            <div class="form-group">
                            <label for="Login">Senha</label>
                            <input type="text" class="form-group" name="password"/>
                            </div>
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </form>
                    </div>          
                </div>
           </div>
        </div>
    </div>
    if
<?php
    require "auxiliar/foot.phtml";
?>