<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>login</title>
</head>
<body>
    <form action="">
        <label for="Login">Login</label>
        <input type="text"/>
        <label for="Login">Senha</label>
        <input type="text"/>
        <button type="submit">Salvar</button>
    </form>
</body>
</html>